// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::database::schema::{battery_logs, tests};

use diesel::prelude::*;
use serde::{Deserialize, Serialize};
use specta::Type;
#[derive(Queryable, Debug, Identifiable, Insertable, Type, Serialize, Deserialize)]
#[diesel(primary_key(record_id))]
#[diesel(table_name = battery_logs)]
pub struct BatteryLog {
    pub record_id: Option<i32>,
    pub id: i32,
    pub port: String,
    pub temperature: i32,
    pub battery_temperature: i32,
    pub electronic_load_temperature: i32,
    pub voltage: i32,
    pub current: i32,
    pub state: String,
    pub status: String,
    pub start_date: Option<String>,
    pub end_date: Option<String>,
    pub test_id: i32,
}

#[derive(Queryable, Debug, Identifiable, Insertable, Type, Serialize, Deserialize)]
#[diesel(primary_key(test_id))]
#[diesel(table_name = tests)]
pub struct Test {
    pub test_id: Option<i32>,
    pub test_name: String,
    pub start_date: String,
}
